#pragma once

#include <linux/bpf.h>
#include <xdp/common/unified_config.h>

enum STATS_TYPE {
    STATS_TYPE_TOTAL_PACKETS,
    STATS_TYPE_UDP_ECHO,
    STATS_TYPE_VPN,
    STATS_TYPE_VPN_ICMP_ECHO,
    STATS_TYPE_VPN_ICMP_SNAT,
    STATS_TYPE_XDP_PASS,
    STATS_TYPE_UDP_HEADER_ERROR,
    STATS_TYPE_VPN_HEADER_ERROR,
    STATS_TYPE_VPN_INNER_IP_ERROR,
    STATS_TYPE_VPN_NON_ICMP,
    STATS_TYPE_VPN_INNER_ICMP_ERROR,
    STATS_TYPE_VPN_NO_EGRESS_IP,
    STATS_TYPE_VPN_ADJUST_HEAD_ERROR,
    STATS_TYPE_VPN_NEW_ETH_ERROR,
    STATS_TYPE_VPN_NEW_IP_ERROR,
    STATS_TYPE_VPN_FIB_LOOKUP_ERROR,
} typedef STATS_TYPE_T;

static __always_inline int inc_pkt_stats(STATS_TYPE_T type);

#include "stats.c"
