// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package bpf

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
	bpfVariableSpecs
}

// bpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	XdpGateway *ebpf.ProgramSpec `ebpf:"xdp_gateway"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	CaptureRuleMap   *ebpf.MapSpec `ebpf:"capture_rule_map"`
	DnatMap          *ebpf.MapSpec `ebpf:"dnat_map"`
	EventsRingbuf    *ebpf.MapSpec `ebpf:"events_ringbuf"`
	FilterRuleMap    *ebpf.MapSpec `ebpf:"filter_rule_map"`
	SnatMap          *ebpf.MapSpec `ebpf:"snat_map"`
	UnifiedConfigMap *ebpf.MapSpec `ebpf:"unified_config_map"`
	XsksMap          *ebpf.MapSpec `ebpf:"xsks_map"`
}

// bpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfVariableSpecs struct {
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
	bpfVariables
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	CaptureRuleMap   *ebpf.Map `ebpf:"capture_rule_map"`
	DnatMap          *ebpf.Map `ebpf:"dnat_map"`
	EventsRingbuf    *ebpf.Map `ebpf:"events_ringbuf"`
	FilterRuleMap    *ebpf.Map `ebpf:"filter_rule_map"`
	SnatMap          *ebpf.Map `ebpf:"snat_map"`
	UnifiedConfigMap *ebpf.Map `ebpf:"unified_config_map"`
	XsksMap          *ebpf.Map `ebpf:"xsks_map"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.CaptureRuleMap,
		m.DnatMap,
		m.EventsRingbuf,
		m.FilterRuleMap,
		m.SnatMap,
		m.UnifiedConfigMap,
		m.XsksMap,
	)
}

// bpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfVariables struct {
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	XdpGateway *ebpf.Program `ebpf:"xdp_gateway"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.XdpGateway,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfeb.o
var _BpfBytes []byte
